services:
  nginx:
    profiles: ['production', 'development', 'local']
    image: simpletaskmanager/web
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
      APP_HOST: app
    build:
      context: ./
      dockerfile: docker/nginx.Dockerfile
    volumes_from:
      - app 
    ports:
      - '8000:80'
    networks:
      - app-net

  ssr:
    profiles: ['production']
    image: simpletaskmanager/app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    ports:
      - '13714:13714'
    networks:
      - app-net
    volumes:
      - ./src:/var/www/html

  node:
    profiles: ['development', 'local']
    image: simpletaskmanager/app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    ports:
      - '13714:13714'
    networks:
      - app-net
    volumes:
      - ./src:/var/www/html

  app:
    profiles: ['production', 'development', 'local']
    image: simpletaskmanager/app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    ports:
      - '9000:9000'
    networks:
      - app-net
    volumes:
      - ./src:/var/www/html
      - ./docker/php.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    command: php-fpm -R

  database:
    profiles: ['development', 'local']
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - app-net
  
  redis:
    profiles: ['production', 'development', 'local']
    image: 'redis:latest'
    ports:
      - 6379:6379

networks:
  app-net:
    driver: bridge
