services:
  nginx:
    image: diedumprun/web
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
      APP_HOST: app
    build:
      context: ./
      dockerfile: docker/nginx.Dockerfile
    volumes_from:
      - app 
    ports:
      - '8000:80'
    networks:
      - app-net

  app:
    image: diedumprun/app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    ports:
      - '9000:9000'
    networks:
      - app-net
    volumes:
      - ./src:/var/www/html
      - ./docker/php.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    command: php-fpm -R

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - app-net

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8003:1025"
      - "8100:8025"

  selenium: 
    image: selenium/standalone-chrome 
    ports: 
      - '4444:4444'
    networks:
      - app-net

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
