name: Deploy to AWS Lightsail

on:
  workflow_run:
    workflows: [Tests]
    types: 
    - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: Login to ECR with Docker
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 932061877711.dkr.ecr.us-east-1.amazonaws.com
          
      - name: Copy production .env config
        run: |
          aws s3 cp s3://jobshop.works/production.env ./src/.env

      - name: Sync production.env configuration file
        run: |
          aws s3 cp s3://jobshop.works/production.env ./src/production.env

      - name: Build, tag and push latest docker images
        run: ENV=prod docker buildx bake --push

      - name: Trigger redeployment from current deployment
        run: |
          aws lightsail create-container-service-deployment \
            --service-name stm \
            --cli-input-json $(aws lightsail get-container-services --service-name stm | jq -c '.containerServices[0].currentDeployment' | jq -c 'del(.version, .state, .createdAt)')
            
