name: Deploy to AWS Lightsail

on:
  workflow_run:
    workflows: ['Tests']
    types: [completed]
    branches:
      - never-for-now-wip
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: Get and write deployment config to file
        id: get-config
        run: |
          aws lightsail get-container-services --service-name stm \
          | jq '.containerServices[0].currentDeployment' \
          > deployment-details.json

      - name: Trigger redeployment
        run: |
          aws lightsail create-container-service-deployment \
            --service-name stm \
            --cli-input-json file://deployment-details.json
