name: Deploy to AWS Lightsail

on:
  workflow_run:
    workflows: ['Tests']
    types: [completed]
    branches:
      - never-for-now-wip
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to ECR with Docker
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 932061877711.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag and push latest docker images
        run: docker buildx bake --push

      - name: Get and write deployment config to file
        id: get-config
        run: |
          echo "deployment=$(aws lightsail get-container-services --service-name stm | jq '.containerServices[0].currentDeployment')" >> $GITHUB_ENV

      - name: Trigger redeployment
        run: |
          echo "${{ env.deployment }}" | aws lightsail create-container-service-deployment \
            --service-name stm \
            --cli-input-json
